name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to target VM
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy application
        env:
          REPO: ${{ github.repository }}
        run: |
            REPO_LOWER=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')
            ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              anna@192.168.56.102 \
              "sudo docker pull ghcr.io/${REPO_LOWER}:${{ github.ref_name }} && \
               sudo sed -i 's|ghcr.io/.*:.*|ghcr.io/${REPO_LOWER}:${{ github.ref_name }}|' \
                 /etc/systemd/system/mywebapp-container.service && \
               sudo systemctl daemon-reload && \
               sudo systemctl restart mywebapp-container"
            

      - name: Wait for service to start
        run: sleep 10

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/deploy_key \
            -o StrictHostKeyChecking=no \
            anna@192.168.56.102 \
            "bash ~/verify.sh"

      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/deploy_key